# Generated by Django 5.2 on 2025-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('fabricante', models.TextField()),
                ('anio_lanzamiento', models.IntegerField()),
                ('tipo', models.TextField()),
                ('region_disponible', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs')),
            ],
        ),
    ]
