# Generated by Django 5.2 on 2025-06-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataformas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='fabricante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='plataformas'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='plataformas'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='region_disponible',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
