# Generated by Django 5.2 on 2025-06-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plataformas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('genero', models.TextField()),
                ('desarrollador', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('clasificacion', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plataformas.plataforma')),
            ],
        ),
    ]
