# Generated by Django 5.2 on 2025-06-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataformas', '0002_alter_plataforma_fabricante_alter_plataforma_logo_and_more'),
        ('Videjouegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='clasificacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='desarrollador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='videojuegos'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='videojuegos'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos', to='Plataformas.plataforma'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
